
SELECT * FROM GAMES_N64
WHERE PLAYERS = '4'
AND GAME_TYPE LIKE '%SHOOTER%'

SELECT * FROM GAMES_N64
WHERE GAME_EFDT >= 2014-01-01
ORDER BY GAME_ID ASC

INSERT INTO GAMES_N64(GAME_EFDT)
	VALUES(CURDATE());
    
UPDATE GAMES_N64
SET GAME_EFDT = CURDATE()
WHERE GAME_ID = '1'
    
    
SELECT * FROM GAMES_N64



CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`games_n64_AFTER_UPDATE` AFTER UPDATE ON `games_n64` FOR EACH ROW
    SET GAME_EFDT = CURDATE()
    games_n64games_n64