/*

SELECT * FROM GAMES_N64
WHERE PLAYERS = '4'
AND GAME_TYPE LIKE '%SHOOTER%'


INSERT INTO GAMES_N64 (GAME_ID, GAME_NAME, PLAYERS, GAME_TYPE, GAME_DEV)
VALUES ('5', 'The Legend of Zelda: The Ocarina of Time', '1', 'Adventure/Fantasy',  'Nintendo')

INSERT INTO GAMES_N64(GAME_EFDT)
	VALUES(CURDATE());
    
    
SELECT * FROM GAMES_N64

*/

CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`games_n64_AFTER_UPDATE` AFTER UPDATE ON `games_n64` FOR EACH ROW
    SET GAME_EFDT = CURDATE()
    games_n64games_n64